author: atkjest
titlebar: 吴继超的个人博客
profile: 嵌入式 | 信息安全

avatar: favicon.jpg
since: 2014

## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://atkjest.me
root: /

rss: /atom.xml
social:
  zhihu: https://www.zhihu.com/people/jichao-wu
  github: https://github.com/atkjest

# Read More
excerpt_link: true

duoshuo_shortname: zone-atkjest
# firebase_url: 请自行修改`source/js/`目录下的favour.js和webstats.js文件
# 将theme.firebase_url的地址修改为自己的firebase App地址


# <meta name="google-site-verification" content="0Hy8JbZfB-YIzE3JroCVmlsXWgUNqLuQQMPzD1KXqSc" />
# <meta name="baidu-site-verification" content="kVDpn43gUF" />
google_analytics: 0Hy8JbZfB-YIzE3JroCVmlsXWgUNqLuQQMPzD1KXqSc
baidu_analytics: kVDpn43gUF
